# Generated by Django 3.1 on 2021-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='video_type',
            field=models.CharField(blank=True, default='movie', max_length=10, null=True),
        ),
    ]
