version: '3'
services:
  # postgres database from existing docker image
  postgres:
    image: postgres:13
    hostname: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ".:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "vfifif"
      PGDATA: "/var/lib/postgresql/data/pgdata" # this is special for mac, otherwise it does not run (permissions issues)
  # My container with admin panel served by django
  admin-panel:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ".:/home"
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    entrypoint: ["movies_admin/manage.py", "runserver", "0.0.0.0:8000"]
    links:
      - postgres
    depends_on:
      - postgres
  # ngnix server
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/configs:/etc/nginx/conf.d
      - ".:/home"
    depends_on:
      - admin-panel
    links:
      - admin-panel
    ports:
      - "80:80"
volumes:
  pgdata: