version: '3'
services:
  # postgres database from existing docker image
  postgres:
    image: postgres:13
    hostname: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ".:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "vfifif"
      PGDATA: "/var/lib/postgresql/data/pgdata" # this is special for mac, otherwise it does not run (permissions issues)
    # My container with admin panel served by django
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ".:/home"
    entrypoint: ["movies_admin/manage.py", "runserver", "0.0.0.0:8000"]
    links:
      - postgres
    depends_on:
      - postgres
volumes:
  pgdata: