version: '3'
services:
  # postgres database from existing docker image
  postgres:
    image: postgres:13
    hostname: postgres
    expose:
      - 5432
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - ".:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "vfifif"
      PGDATA: "/var/lib/postgresql/data/pgdata" # this is special for mac, otherwise it does not run (permissions issues)
  # django admins panel
  admin-panel:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - static:/home/static
  # nginx server
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/configs:/etc/nginx/conf.d
      - static:/var/www/static/
    depends_on:
      - admin-panel
    links:
      - admin-panel
    ports:
      - "80:80"
  # elasticserch db
  elastic_admin:
    image: elasticsearch:7.7.0
    environment:
      discovery.type: single-node
      # env for ui:
      #http.cors.enabled: true
      #http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358
      #http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      #http.cors.allow-credentials: true
    expose:
      - 9200
      - 9300
    depends_on:
      - admin-panel
    links:
      - admin-panel
    volumes:
      - ./postgres_to_es:/home/postgres_to_es/
      #- something to start them
volumes:
  pgdata:
  static: