version: '3'
services:
  # postgres database from existing docker image
  postgres:
    image: postgres:13
    hostname: postgres
    expose:
      - 5432
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - ".:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "vfifif"
      PGDATA: "/var/lib/postgresql/data/pgdata" # this is special for mac, otherwise it does not run (permissions issues)
  # django admins panel
  admin-panel:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/configs:/etc/nginx/conf.d
      - "./static:/var/www/static/"
    depends_on:
      - admin-panel
    links:
      - admin-panel
    ports:
      - "80:80"
volumes:
  pgdata: